#!/bin/bash

# Proxy tool for terminal commands.

function usage()
{
	echo """
Usage: cproxy command args
"""
}

while (( "$#" )); do
	case "$1" in
	-h|--help)
		usage
		exit
		;;
	*)
		break
		;;
	esac
done

if [ ! -f "/etc/cproxy.conf" ]; then
	echo "proxy configuration file is missing."
	usage
	exit
fi

. /etc/cproxy.conf

if [ ! -z ${http_proxy} ]; then
	export http_proxy=${http_proxy}
fi
if [ ! -z ${https_proxy} ]; then
	export https_proxy=${https_proxy}
fi
if [ ! -z ${all_proxy} ]; then
	export all_proxy=${all_proxy}
fi
("${@}")